### ISSUE TITLE
modalConsoleHistoryRepository not found

### ISSUE THREAD

**Issue by kolbykruger** [sergant210/modalConsole#1]
Hi there,

Neat extra. I am getting an error when executing the code in the modalConsole.

I get a string printed in the console window:
`{"success":false,"message":"Class \"modalConsoleHistoryRepository\" is not found!","total":0,"data":[],"object":[]}`

As well as a popup error:
`Class "modalConsoleHistoryRepository" is not found!`

I am printing a simple message for testing purposes:
`echo "message";`

**Comment by sergant210** [comment]
Fixed. Remove the package and install it agian.
